from __future__ import annotations

import json
import logging
from html import escape
from typing import Any
from urllib.parse import quote

import httpx
from sqlalchemy.orm import Session

from app.core.config import Settings, get_settings
from app.db.base import utc_now
from app.models import GeneratedDocument, Project

logger = logging.getLogger(__name__)

AUD_READY_SUBJECT = "Your AUD Has Been Generated"
AUD_READY_METADATA_KEY = "email_notification"
AUD_READY_SENT_STATUS = "aud_ready_sent"


def clean_email_field(value: str | None, fallback: str = "") -> str:
    normalized = " ".join((value or "").split())
    return normalized or fallback


def clean_optional_setting(value: str | None) -> str | None:
    if value is None:
        return None

    stripped = value.strip()
    return stripped or None


def get_email_ssl_verify(settings: Settings) -> bool | str:
    if not settings.EMAIL_NOTIFICATION_VERIFY_SSL:
        return False

    ca_bundle = clean_optional_setting(settings.EMAIL_NOTIFICATION_CA_BUNDLE)
    return ca_bundle or True


def build_generated_document_download_url(
    project: Project,
    generated_document: GeneratedDocument,
    settings: Settings | None = None,
) -> str | None:
    resolved_settings = settings or get_settings()
    base_url = clean_optional_setting(
        resolved_settings.EMAIL_NOTIFICATION_DOWNLOAD_BASE_URL
    )
    if base_url is None:
        return None

    project_id = quote(clean_email_field(project.id), safe="")
    document_id = quote(clean_email_field(generated_document.id), safe="")
    if not project_id or not document_id:
        return None

    return (
        f"{base_url.rstrip('/')}/projects/{project_id}/generated-documents/"
        f"{document_id}/download"
    )


def build_aud_ready_email_payload(
    project: Project,
    settings: Settings | None = None,
    *,
    download_url: str | None = None,
) -> dict[str, Any] | None:
    resolved_settings = settings or get_settings()
    to_email = clean_email_field(project.email_id)
    if not to_email:
        return None

    author_name = clean_email_field(project.name, "there")
    customer_name = clean_email_field(project.customer_name, "the selected customer")
    module_name = clean_email_field(project.module_name, "selected module")
    download_text_line = f"\n\nDownload link: {download_url}" if download_url else ""

    body = (
        f"Hello {author_name},\n\n"
        f"Your requested AUD for {customer_name} - {module_name} is now ready "
        "to download."
        f"{download_text_line}\n\n"
        "This notification is generated by AUDacle."
    )
    body_html = build_aud_ready_email_html(
        author_name=author_name,
        customer_name=customer_name,
        module_name=module_name,
        download_url=download_url,
    )

    return {
        "to_email": to_email,
        "from_email": clean_email_field(
            resolved_settings.EMAIL_NOTIFICATION_FROM,
            "audacle@oracle.com",
        ),
        "subject": AUD_READY_SUBJECT,
        "body": body,
        "body_html": body_html,
        "cc": None,
        "bcc": None,
        "replyto": None,
    }


def build_aud_ready_email_html(
    *,
    author_name: str,
    customer_name: str,
    module_name: str,
    download_url: str | None = None,
) -> str:
    author_html = escape(author_name)
    customer_html = escape(customer_name)
    module_html = escape(module_name)
    download_html = ""
    if download_url:
        download_href = escape(download_url, quote=True)
        download_text = escape(download_url)
        download_html = (
            '<p style="margin:22px 0 8px; font-size:15px; line-height:1.6;">'
            f'<a href="{download_href}" style="display:inline-block; '
            "background-color:#305CDE; color:#ffffff; padding:12px 18px; "
            "border-radius:6px; text-decoration:none; font-size:14px; "
            'font-weight:600;">Download AUD</a></p>'
            '<p style="margin:0 0 20px; font-size:12px; line-height:1.5; '
            'color:#6b7280; word-break:break-all;">'
            f'<a href="{download_href}" style="color:#305CDE; '
            f'text-decoration:none;">{download_text}</a></p>'
        )

    return (
        '<html><body style="margin:0; padding:0; background-color:#f4f6f8; '
        'font-family:Arial, Helvetica, sans-serif; color:#1f2937;">'
        '<table width="100%" cellpadding="0" cellspacing="0" '
        'style="background-color:#f4f6f8; padding:24px 0;"><tr><td align="center">'
        '<table width="600" cellpadding="0" cellspacing="0" '
        'style="background-color:#ffffff; border-radius:10px; overflow:hidden; '
        'border:1px solid #e5e7eb;"><tr><td style="background-color:#305CDE; '
        'padding:22px 28px;"><h2 style="margin:0; color:#ffffff; font-size:22px; '
        'font-weight:600;">Your AUD Is Now Available</h2></td></tr><tr><td '
        'style="padding:28px;"><p style="margin:0 0 16px; font-size:15px; '
        f'line-height:1.6;">Hello {author_html},</p><p style="margin:0 0 20px; '
        'font-size:15px; line-height:1.6;">Your requested AUD has been generated '
        f"successfully and is now ready to download.</p>{download_html}<table "
        'width="100%" cellpadding="0" cellspacing="0" style="margin:20px 0; '
        'border-collapse:collapse; background-color:#f9fafb; border:1px solid '
        '#e5e7eb; border-radius:8px;"><tr><td style="padding:14px 16px; '
        'font-size:14px; color:#6b7280; border-bottom:1px solid #e5e7eb;">'
        'Customer Name</td><td style="padding:14px 16px; font-size:14px; '
        f'font-weight:600; color:#111827; border-bottom:1px solid #e5e7eb;">{customer_html}'
        '</td></tr><tr><td style="padding:14px 16px; font-size:14px; '
        'color:#6b7280;">Module Name</td><td style="padding:14px 16px; '
        f'font-size:14px; font-weight:600; color:#111827;">{module_html}</td></tr>'
        '</table><p style="margin:20px 0 0; font-size:14px; line-height:1.6; '
        'color:#4b5563;">This notification is generated by <strong>AUDacle</strong>.'
        '</p></td></tr><tr><td style="padding:16px 28px; background-color:#f9fafb; '
        'border-top:1px solid #e5e7eb;"><p style="margin:0; font-size:12px; '
        'color:#6b7280;">Please do not reply to this automated notification.</p>'
        "</td></tr></table></td></tr></table></body></html>"
    )


class EmailNotificationService:
    def __init__(
        self,
        settings: Settings | None = None,
        client: httpx.Client | None = None,
    ) -> None:
        self.settings = settings or get_settings()
        self.client = client

    def send_aud_ready_notification(
        self,
        project: Project,
        generated_document: GeneratedDocument,
    ) -> bool:
        if not self.settings.EMAIL_NOTIFICATIONS_ENABLED:
            logger.info(
                "AUD ready email notifications are disabled for project %s.",
                project.id,
            )
            return False

        notification_url = clean_email_field(self.settings.EMAIL_NOTIFICATION_URL)
        if not notification_url:
            logger.warning(
                "AUD ready email notification skipped for project %s because "
                "EMAIL_NOTIFICATION_URL is not configured.",
                project.id,
            )
            return False

        download_url = build_generated_document_download_url(
            project,
            generated_document,
            self.settings,
        )
        payload = build_aud_ready_email_payload(
            project,
            self.settings,
            download_url=download_url,
        )
        if payload is None:
            logger.info(
                "AUD ready email notification skipped for project %s because "
                "email_id is not available.",
                project.id,
            )
            return False

        try:
            response = self._post(notification_url, payload)
            response.raise_for_status()
        except Exception:
            logger.exception(
                "AUD ready email notification failed for project %s and document %s.",
                project.id,
                generated_document.id,
            )
            return False

        logger.info(
            "AUD ready email notification sent for project %s and document %s.",
            project.id,
            generated_document.id,
        )
        return True

    def _post(self, notification_url: str, payload: dict[str, Any]) -> httpx.Response:
        if self.client is not None:
            return self.client.post(notification_url, json=payload)

        timeout_seconds = max(self.settings.EMAIL_NOTIFICATION_TIMEOUT_SECONDS, 0.1)
        with httpx.Client(
            timeout=timeout_seconds,
            verify=get_email_ssl_verify(self.settings),
            trust_env=self.settings.EMAIL_NOTIFICATION_TRUST_ENV,
        ) as client:
            return client.post(notification_url, json=payload)


def parse_document_metadata(generated_document: GeneratedDocument) -> dict[str, Any]:
    if not generated_document.metadata_json:
        return {}

    try:
        parsed = json.loads(generated_document.metadata_json)
    except json.JSONDecodeError:
        return {}

    return parsed if isinstance(parsed, dict) else {}


def was_aud_ready_notification_sent(generated_document: GeneratedDocument) -> bool:
    metadata = parse_document_metadata(generated_document)
    notification_metadata = metadata.get(AUD_READY_METADATA_KEY)
    return (
        isinstance(notification_metadata, dict)
        and notification_metadata.get("status") == AUD_READY_SENT_STATUS
    )


def mark_aud_ready_notification_sent(
    session: Session,
    generated_document: GeneratedDocument,
) -> None:
    metadata = parse_document_metadata(generated_document)
    metadata[AUD_READY_METADATA_KEY] = {
        "status": AUD_READY_SENT_STATUS,
        "sent_at": utc_now().isoformat(),
    }
    generated_document.metadata_json = json.dumps(metadata)
    session.add(generated_document)
    session.commit()
    session.refresh(generated_document)


def notify_aud_ready_for_document(
    session: Session,
    project_id: str,
    generated_document: GeneratedDocument,
    service: EmailNotificationService | None = None,
) -> bool:
    if was_aud_ready_notification_sent(generated_document):
        return False

    project = session.get(Project, project_id)
    if project is None:
        logger.error(
            "AUD ready email notification skipped because project %s was not found.",
            project_id,
        )
        return False

    try:
        sent = (service or EmailNotificationService()).send_aud_ready_notification(
            project,
            generated_document,
        )
    except Exception:
        logger.exception(
            "AUD ready email notification failed unexpectedly for project %s "
            "and document %s.",
            project_id,
            generated_document.id,
        )
        return False

    if not sent:
        return False

    mark_aud_ready_notification_sent(session, generated_document)
    return True
